### ISSUE TITLE
Being asked to fill optional Cursor field in connection configuration

### ISSUE THREAD

**Issue by pandeyganesh-dc** [dat-labs/verified-sources#30]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

While configuring connection for `Website crawler -> OpenAI -> qdrant`, I am asked to to fill `Cursor Field` even though I have chose `FULL_REFRESH` in `ReadSyncMode`.

### Steps to Reproduce

- Create website crawler as source
- choose any generator
- choose any destination
- edit the connection for any stream
- choose `FULL_REFRESH` in `ReadSyncMode`
- leave Cursor Field empty as not needed
- Fill in all the other details required
- press submit

### Screenshots

![image](https://github.com/user-attachments/assets/7e5969e6-6048-4ce5-bf66-a4b29fdd1248)

### Environment

OS: Arch Linux
Browser: Google Chrome

**Comment by dc-rahul** [comment]
Cursor field has been moved to individual sources. This ticket can be closed

**Comment by pandeyganesh-dc** [comment]
Thanks, checked it and it has been resolved. Closing the issue.
