### ISSUE TITLE
Mandatory Dir Uris field is accpeting empty input also

### ISSUE THREAD

**Issue by pandeyganesh-dc** [dat-labs/verified-sources#31]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

While configuring `Google Drive -> OpenAI -> qdrant`,  We need to enter the path of the google directory from where we need to fetch the data in `Dir Uris`.  So, I entered the path and pressed submit and the tab got closed and then i ran the connection but it failed. I realized it later that we need to press enter too after entering the dir. But the problem is, pressing submit did not raise `field required` prompt over the field. 

### Steps to Reproduce

- Configure `Google Drive` as source
- choose any generator and destination
- Configure the Google Drive and do not fill `Dir Uris` 
- press submit

Won't get any restriction to fill this mandatory field.

### Environment

OS: Arch Linux
Browser: Google Chrome

**Comment by dc-rahul** [comment]
The solution would be to mark dir_uris field with `minimum_items` = 1

**Comment by pandeyganesh-dc** [comment]
Thanks, the problem has been resolved.
